export const menu = [
  {
    category: "MOJITO & JUICES | منطقة الانتعاش",
    className: "mojito",
    items: [
      { name: "موهيتو فريز", price: 22000 },
      { name: "موهيتو كرز", price: 22000 },
      { name: "موهيتو رمان", price: 22000 },
      { name: "موهيتو عنب", price: 22000 },
      { name: "موهيتو بلو", price: 22000 },
      { name: "موهيتو مارشميلو", price: 22000 },
      { name: "موهيتو بلو بيري", price: 25000 },
      { name: "موهيتو بلو هاواي", price: 25000 },
      { name: "موهيتو فانيل تشيري", price: 25000 },
      { name: "موهيتو بلوبيري وفريز", price: 25000 },
      { name: "ميكس فانيل وعنب", price: 25000 },
      { name: "بولو", price: 25000 },
      { name: "عصير فريز", price: 25000 },
      { name: "عصير هاواي", price: 25000 },
      { name: "موز وحليب وعسل", price: 25000 },
      { name: "عصير فواكه كوكتيل", price: 30000 },
      { name: "سلطة فواكه", price: 40000 },
      { name: "بيروت بير تنك", price: 35000 },
      { name: "افاميا", price: 28000 },
      { name: "فروتي كرتون", price: 3000 },
      { name: "فروتي بلاستيك", price: 6000 },
      { name: "فروتي زجاج", price: 6000 },
      { name: "ميلك تشوكلت فرابي", price: 25000 },
      { name: "ميلك لوتس فرابي", price: 25000 },
    ],
  },
  {
    category: "HOT DRINKS | المشروبات الساخنة",
    className: "hotdrinks",
    items: [
      { name: "قهوة كريمي", price: 8000 },
      { name: "كابتشينو", price: 7000 },
      { name: "3in1", price: 7000 },
      { name: "هوت شوكليت", price: 10000 },
      { name: "هوت لوتس", price: 10000 },
      { name: "متة", price: 8000 },
      { name: "شاي", price: 6000 },
      { name: "زهورات", price: 6000 },
      { name: "كمون بليمون", price: 6000 },
      { name: "قهوة", price: 6000 },
      { name: "نسكافيه", price: 6000 },
      { name: "كاسة اندومي", price: 10000 },
    ],
  },
  {
    category: "WORLD CUP FOODS | مأكولات كأس العالم",
    className: "worldcup",
    items: [
      { name: "وجبة طوشكا", price: 40000 },
      { name: "وجبة سجق", price: 40000 },
      { name: "بطاطا كاسات", price: 7000 },
      { name: "منقوشة سجق", price: 15000 },
      { name: "جبنة وحر", price: 6000 },
      { name: "جبنة", price: 6000 },
      { name: "محمرة", price: 5000 },
      { name: "زعتر", price: 5000 },
      { name: "قشقوان وحر", price: 7000 },
      { name: "مرتديلا وقشقوان", price: 10000 },
      { name: "بيتزا", price: 10000 },
      { name: "لحمة", price: 10000 },
      { name: "صحن بطاطا", price: 15000 },
      { name: "بيتزا صغير", price: 35000 },
      { name: "بيتزا وسط", price: 60000 },
      { name: "بيتزا كبير", price: 80000 },
      { name: "بيتزا سجق وسط", price: 75000 },
      { name: "طلياني", price: 15000 },
      { name: "قشقوان", price: 9000 },
      { name: "بطاطا عادي سندويش", price: 15000 },
      { name: "بطاطا دبل سندويش", price: 20000 },
    ],
  },
  {
    category: "SHISHA | ركن الأركيلة",
    className: "shisha",
    items: [
      { name: "أركيلة فاخر", price: 25000 },
      { name: "أركيلة مزايا", price: 25000 },
      { name: "أركيلة بولو", price: 25000 },
      { name: "أركيلة تفاحتين نخلة", price: 30000 },
      { name: "أركيلة بالفواكه - برتقال", price: 50000 },
      { name: "أركيلة بالفواكه - بوملي", price: 60000 },
    ],
  },
  {
    category: "BURGER | همبرغو",
    className: "burger",
    items: [
      { name: "وجبة أوريجينال برغر", price: 55000 },
      { name: "أوريجينال برغر", price: 45000 },
      { name: "وجبة كلاسيك برغر", price: 55000 },
      { name: "كلاسيك برغر", price: 45000 },
      { name: "تشيلي برغر", price: 45000 },
      { name: "وجبة تشيلي برغر", price: 55000 },
    ],
  },
];
